### ISSUE TITLE
CHaP cardano-ledger still behind ghc-next-packages in some ways

### ISSUE THREAD

**Issue by AriFordsham** [input-output-hk/cardano-haskell-packages#112]
I used ghc-next-packages (now seemingly abandoned) to upgrade a project (https://github.com/mlabs-haskell/plutus-simple-model) to GHC 9.4. I had to disable the tests because they used `plutus-tx-plugin`, for which there was no GHC 9-compatible version on ghc-next-packages.

I am now attempting to switch to CHaP and upgrade the test suite.

However, ghc-next-packages was based off of the `master` branch of `cardano-ledger`, and CHaP is based off of the `release/1.1.x` branch. There are [changes in `master` which are not in `release/1.1.x`](https://github.com/input-output-hk/cardano-ledger/compare/release/1.1.x...master).

What's currently breaking build for me is the renaming of `Cardano.Ledger.Alonzo.TxWitnesses` to `TxWits`, which is only on `master`. I'm loathe to change this back, as I'm sure this is not the only thing, and I'm not keen to go down an endless rabbit hole of undoig work already done.

What is the recommended way forward here?

cc @angerman

**Comment by AriFordsham** [comment]
More precisely, ghc-next-packages used `ddbd9b8969c1adab6d943282ba07cf248d92ebe4` - [diff](https://github.com/input-output-hk/cardano-ledger/compare/release/1.1.x...ddbd9b8969c1adab6d943282ba07cf248d92ebe4)

**Comment by michaelpj** [comment]
`ghc-next-packages` is dead, I think. There will hopefully be a new release of the ledger packages before long. We were in a bad state where various unreleased versions of them were in use, we're trying to fix that.

Just so you're aware, we're currently trying to get things working with GHC 9.2, and there's a fair bit more to do. We haven't even _looked_ at 9.4 support, so I'd be very surprised if that works.

**Comment by AriFordsham** [comment]
Sorry, my mistake. I meant 9.2.4.

So best is to just hold on until a post-1.1 relesae?

**Comment by michaelpj** [comment]
We're trying to bubble up 9.2.4 support currently. Hopefully there will be a ledger release before long, then we need to do the same for `ouroboros-network` and `cardano-node` in sequence. Unclear how long that will take.

**Comment by michaelpj** [comment]
I think there's nothing for us to do here.
