### ISSUE TITLE
Patched: inline-r-1.0.0.0.0.0.0.1

### ISSUE THREAD

**Issue by bezirg** [input-output-hk/cardano-haskell-packages#115]
It allows nix-installed R libraries to be visible to `inline-r` Haskell library.

Can deprecate when upstream makes a new release to Hackage.

**Comment by michaelpj** [comment]
Still hasn't been released.

**Comment by andreabedini** [comment]
@ConnorBaker do you know if there's a new release in the pipeline? Specifically we need this change https://github.com/tweag/HaskellR/commit/53ce6887d8043252a068bc0a7db438abd4cfdc52

**Comment by michaelpj** [comment]
`inline-r` got released.
