### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by jonathanfishbein1** [input-output-hk/cardano-haskell-packages#116]
Warning: Caught exception during _mirrors lookup:res_query: does not exist
(Connection refused)
Warning: No mirrors found for
https://input-output-hk.github.io/cardano-haskell-packages
dieVerbatim: user error (Error: cabal:
'/nix/store/vd4p2dirng26fkfk024l00hvz0z7f5ks-curl-7.84.0-bin/bin/curl' exited
with an error:
curl: (6) Could not resolve host: input-output-hk.github.io
)

**Comment by andreabedini** [comment]
Hi there,

reading `/nix/store/vd4p2dirng26fkfk024l00hvz0z7f5ks-curl-7.84.0-bin/bin/curl` I take that foliage might be running inside nix. During a nix build, processes are not allow to use the network, so any call to curl will fail.

May I ask what are you trying to achieve?
