### ISSUE TITLE
Consider running `build` on PRs

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-haskell-packages#13]
I think at the moment it only runs on `main`. But it's probably useful (if expensive) to run on PRs, probably some kinds of malformed metadata will only be caught by actually trying to build the repo?

**Comment by andreabedini** [comment]
Yes, we should. But we should also save the repo as an artifact after the build (so one can fetch it and troubleshoot). At this moment, uploading the artifact and publishing are a bit interweened. I can work to disentagle them.

Or one could push the build repo to new branch per build/PR?

**Comment by michaelpj** [comment]
Saving the artifact sounds sensible so long as it's easy enough to get? Although tbh people can probably reproduce by building locally. It's like CI: you mostly just try and reproduce the problem locally.
