### ISSUE TITLE
Add a workflow to update the flake inputs occasionally

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-haskell-packages#166]
Use https://github.com/DeterminateSystems/update-flake-lock .

In particular, we want to update our `hackage.nix` pin relatively frequently so we're generally building against a new-ish Hackage. The others we can probably update manually.

**Comment by michaelpj** [comment]
We probably do need to do the token stuff since we definitely want the CI to run so we can test the update.

**Comment by andreabedini** [comment]
> In particular, we want to update our `hackage.nix` pin relatively frequently so we're generally building against a new-ish Hackage. The others we can probably update manually.

As mentioned in #179 we could also do `--update-input hackage-nix` to always build with the newest hackage.nix.

**Comment by michaelpj** [comment]
As I said there, I think that will force too much rebuilding. The chance that something somewhere in `cardano-node`'s dependency tree will be different is high, and now you're rebuilding the world...

**Comment by andreabedini** [comment]
_Updating our hackage.nix pin relatively frequently_ is also more rebuilding. Anyway, happy to keep it a separate CI step, with `update-flake-lock`.

**Comment by michaelpj** [comment]
True. I guess it depends on the relative frequency of the update workflow versus people publishing packages. It also moves the cost of rebuilding Hackage stuff to when the update workflow runs rather than on pepole's PRs.
