### ISSUE TITLE
scripts/add-from-github.sh -- add revision field

### ISSUE THREAD

**Issue by angerman** [input-output-hk/cardano-haskell-packages#18]
It would be nice if one could do something like:

```
./scripts/add-from-github.sh https://github.com/input-output-hk/nothunks 45d066c4f47400e645bda7dc0ffe5070bd2baf42 -rev 3
```
and have this produce `$version.0.0.0.3`.

**Comment by andreabedini** [comment]
I guess this can only work when adding a single package? (e.g. not using subdirs)
