### ISSUE TITLE
cardano-api

### ISSUE THREAD

**Issue by L-as** [input-output-hk/cardano-haskell-packages#28]
How come cardano-api isn't here?

**Comment by michaelpj** [comment]
This is currently populated with what's needed for `cardano-node` at its last release. That's so we can get it to the point where this works with `cardano-node`, and make a decision about whether we're going to commit with this. Then we can move on to using it more widely, including adding the packages from `cardano-node` itself.

**Comment by L-as** [comment]
I'm asking because cardano-api has a sublibrary and that seems not to work with Cabal or anything really.

**Comment by michaelpj** [comment]
> I'm asking because cardano-api has a sublibrary and that seems not to work well with Cabal or anything really when in a hackage repository.

Hmm, if so that's news to me. I thought it worked fine, but we should check.

**Comment by L-as** [comment]
@andreabedini try exactDeps = true and cabal build in the development shell. Might happen with exactDeps = false too.

**Comment by michaelpj** [comment]
It's there.
