### ISSUE TITLE
How do we manage access rights?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-haskell-packages#33]
Ideally we want people to be able to merge their own PRs to their own packages, but we (maybe?) care about people pushing malicious packages? Or not.

We could use `CODEOWNERS` as a fairly lightweight permissions system.

**Comment by michaelpj** [comment]
At the very least: anyone who is releasing package X should be able to merge a PR touching X.

**Comment by michaelpj** [comment]
Anything else is an unacceptable drag IMO.

**Comment by ch1bo** [comment]
The scope of the PRs would be mostly bumping to new versions right? I don't think that we need to permit this. After all, the version to be bumped to is already released and anyone should be able to wave through that PR.

**Comment by michaelpj** [comment]
The problem is that we foliage just associates versions with tarballs. So there's nothing stopping you from releasing a version with a bad/malicious tarball.

**Comment by coot** [comment]
I agree with @michaelpj that we should care about access rights.  :+1: on using `CODEOWNERS` file, although it will require extra step: one will need to approve ones own PR, which I think it's fine.  It will be quite easy to maintain as `CODEOWNERS` files [support directories](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file).

**Comment by michaelpj** [comment]
Hmm, it would be ideal if there was a way to not require approval if the PR creator is in CODEOWNERS.

**Comment by michaelpj** [comment]
We've started with a CODEOWNERS file. It's not mandatory to get a review yet, so I'll leave this open for now.

**Comment by michaelpj** [comment]
I think the current setup is fine and we can mess with it later if we need to.
