### ISSUE TITLE
Tips on debugging/ inspection when I can't find the right version.

### ISSUE THREAD

**Issue by waalge** [input-output-hk/cardano-haskell-packages#334]
I can't see the right version of `cardano-crypto-class` no matter what I try. I'm also just guessing. 

Context: 

I'm trying to make a haskell repo that depends on the lastest version of plutus. This is not yet in CHaPs. 
Starting from the plutus repo, nix/ haskell.nix, `nix develop` all behave correctly. I can open a shell and build.
I can make a new subdir, create a repo that uses the new elliptic curve pair methods - all works fine.

When I try to take the nix code into a new repo (of which there is quite a lot) and cut out the plutus-repo-specific parts, things go wrong. 
Depending on what I do either I can't drop into a shell, or once I do, I can't see the right version of `cardano-crypto-class`. 
Maybe I've got rid of something important.

**Comment by waalge** [comment]
Some of the permutations I tried, with some error messages in the commit messages
https://github.com/waalge/plutus-template/commits/main

**Comment by andreabedini** [comment]
In this output https://github.com/waalge/plutus-template/commit/81a13728ed7faeffc87af73e4a0e90519a6e7ddf cabal is saying that it cannot find `libblst-any`, so it cannot choose `cardano-crypto-class-2.1.1.0` which is the only version which can work with `plutus-example` given `cardano-crypto-class>=2.1.2`. The subsequent attempts showed the same problem.

libblst is provided in the crypto overlay provided by [iohk-nix](https://github.com/input-output-hk/iohk-nix).

If you cannot fix that I suggest you to start with a much simpler setup which you can understand and control. I won't have time today to look at this in any detail unfortunately.

**Comment by waalge** [comment]
I've tried many attempts getting a flake to run plutus. Starting from scratch was really a non-starter - agreed that this would be better were it feasible for me. At least starting with plutus's nix setup, it is starting something that works. 

--- 

After inspecting the flake locks between my version and the version in plutus of the `iohk-nix`, I can see there is indeed a difference in the hash. 
Pinning the version of iohk-nix in the flake leads to getting a shell. Something goes wrong here (wrt plutus flake). 
https://github.com/input-output-hk/iohk-nix/commit/e4b4589168c6abc698c49faba130dda65d908051

---

Thanks for engaging on this!

**Comment by andreabedini** [comment]
Yeah I remember that change causing some issues (or solving some issues? I don't remember 😂)
