### ISSUE TITLE
protolude-0.3.3.0.0.0.0.1's `repo` field contains a trailing slash

### ISSUE THREAD

**Issue by fraser-iohk** [input-output-hk/cardano-haskell-packages#405]
There's a trailing slash in the `repo` field in protolude-0.3.3.0.0.0.0.1's `meta.toml` ([link](https://github.com/input-output-hk/cardano-haskell-packages/blob/main/_sources/protolude/0.3.3.0.0.0.0.1/meta.toml)), which makes it slightly more difficult for automated tools that look at `meta.toml`s to parse owner / repository information. Could this trailing slash be removed safely without causing breakage to CHaP?

**Comment by michaelpj** [comment]
@andreabedini WDYT?

**Comment by andreabedini** [comment]
Yes, it should be fine. Make a PR to fix it let the CI will verify the index is unchanged.
