### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-haskell-packages#82]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

* [ ] Explain how to make a contribution (Contributing MD)
* [x] Include the Standard Code of Conduct
* [x] Use the Apache 2.0 License or agreed alternative
* [ ] Identify the Core Maintainers

**Comment by andreabedini** [comment]
> Explain how to make a contribution (Contributing MD)

Most of the readme is about contributing packages to the cardano-haskell-packages repository. E.g.
- [How to add a new package version to CHaP](https://github.com/input-output-hk/cardano-haskell-packages#how-to-add-a-new-package-version-to-chap)
- [How do I add a patched versions of a Hackage package to CHaP?](https://github.com/input-output-hk/cardano-haskell-packages#how-do-i-add-a-patched-versions-of-a-hackage-package-to-chap)
- [How to test changes to CHaP](https://github.com/input-output-hk/cardano-haskell-packages#how-to-test-changes-to-chap)

Do we need to move this into a separate file?

**Comment by coot** [comment]
I don't think so.  This repo has two purposes: one it's a public API for adding new packages (which is very well described in `README.md`) and secondly the infrastructure which allows us to run `CHaP`. It would be nice to add at least a minimal `CONTRIBUTING.md` which describes how to contribute to the infrastructure and identifies the core maintainers etc.
